// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `angular-cli.json`.

export const environment = {
  production: false,
  googleMapsApiKey: '',
  storageSecretKey: 'secret-for-storage',
  api: 'http://dev.mc4.com.bo:8082',
  apiClient: 'http://dev.mc4.com.bo:8082',
  apiRRHH:'http://dev.mc4.com.bo:8081',
  appLogProccess: 'APLICACION_WEB',
  moduleName: 'Módulo de Historia Clínica',
  socketUrl: 'ws://modhceweb-qa.prosalud.org:80',
  backend: {
    apiLogin: '/mu/signin',
    apiLogout: '/mu/logout',
    apiLoginKeycloak: '/mu/signin-by-keycloak',
    apiChangePass: '/mu/change-password',
    apiRecursos: '/api/resource',
    userApi: '/api/v1/users',
    participanteApi: '/api/participant',
    medicineApi:'/api/medicine',
    horarioAtencionApi: '/api/attending_hours',
    contingenciaCamaraApi: '/api/contingency_chamber',
    certificadoApi: '/api/certificate',
    mensajeApi: '/api/message',
    ordenApi: '/api/order',
    businessApi: '/api/business',
    reportService: '/api/reporteria',
  },
  backendV2: {
    userApi: '/api/v1/users',
    roleApi: '/api/v1/role',
    businessUnitsApi: '/api/v1/business-units',
    regionsApi: '/api/v1/regions',
    moduleApi: '/api/v1/modules',
    centerCosteApi: '/api/v1/centers-of-costs',
    domainApi: '/api/v1/domain',
    actionApi: '/api/v1/action',
    themeApi: '/api/v1/theme',
    resourceApi: '/api/v1/resource',
    parameterApi: '/api/v1/parameter',
    parameterGroupApi: '/api/v1/parameter-group',
    utilApi: '/api/v1/utils',
    logApi: '/api/v1/log',
    auditConfigurationApi: '/api/v1/audit-configurations',
    auditDataBaseApi: '/api/v1/audit-databases',
    auditApi: '/api/v1/audits',
    reportApi: '/api/v1/reports',
    modulesApi: '/api/v1/modules',
    patientApi: '/api/v1/patient',
    patientInsuranceApi: '/api/v1/patient-insurance',
    employee:'/api/v1/employee',
    medic:'/api/v1/medic',
    room:'/api/v1/room',
    medicroom:'/api/v1/medic-room',
    quoteApi:'/api/v1/quote',
    pharmacyApi: '/api/v1/pharmacy',
    emailApi:'/api/v1/mail',
    guestApi:'/api/v1/guest',
    recurrencyApi:'/api/v1/recurrency',
    regionApi:'/api/v1/regions',
    shiftAssignmentApi:'/api/v1/shift-assignment',
    excelApi:'/api/v1/xls',
    cie10Api: '/api/v1/cie10',
    cie10FavoriteApi: '/api/v1/cie10-favorite',
    vaccinationApi: '/api/v1/vaccination',
    nurse: '/api/v1/nurse',
    rulesVaccinationApi: '/api/v1/rules-vaccination',
    vaccinationPatientApi: '/api/v1/vaccination-patient',
    imcParamApi: '/api/v1/imc',
    riskFactorApi: '/api/v1/risk-factor',
    allergiesPatientApi: '/api/v1/allergies-patient',
    complementaryExamApi: '/api/v1/complementary-exam',
    complementaryExamDetailsApi: '/api/v1/complementary-exam-details',
    ambulatoryApi: '/api/v1/ambulatory',
    cie10AmbulatoryApi: '/api/v1/cie-ambulatory',
    complementaryExamExternApi: '/api/v1/complementary-exam-extern',


    establishment: '/api/v1/establishment',
    floor: '/api/v1/floor',
    patientRoom: '/api/v1/patient-room',
    bed: '/api/v1/bed',
    medicalDocumentsApi: '/api/v1/medical-documents',
    vitalSign: '/api/v1/vital-sign',
    growthMonitoring: '/api/v1/growth-monitoring',
    nursingCare: '/api/v1/nursing-care',
    nurseShift: '/api/v1/nurse-shift',
    medicalPrescriptionApi: '/api/v1/medical-prescription',
    medicalPrescriptionProductApi: '/api/v1/medical-prescription-product',
    notifications: '/api/v1/notifications',
    configNotifications: '/api/v1/notifications-config',
    notificationDetails: '/api/v1/notification-details',
    patientRiskFactorApi: '/api/v1/patient-risk-factor',
    ruleRiskFactorApi: '/api/v1/rule-risk-factor',
    medicalAdmissionReferenceApi: '/api/v1/medical-admissions',
    medicalReferenceApi: '/api/v1/medical-reference',
    medicalTransferReferenceApi: '/api/v1/medical-transfers',
    responsibleModUser: '/api/v1/mod-user/responsible',
  },
  backendSocket: {
    notifications: '/ws/notifications',
  },
  keycloakConfig: {
    url: 'https://id.mc4.com.bo:8443/',
    realm: 'prosalud',
    clientId: 'user-web-client',
  },
  modUserHost: 'http://192.168.6.52:4200/home',
};
